export const desserts = [
  {
    title: 'waffle with berries',
    category: 'waffle',
    price: 6.5,
    imgMobile: '/src/assets/images/image-waffle-mobile.jpg',
    imgTablet: '/src/assets/images/image-waffle-tablet.jpg',
    imgDesktop: '/src/assets/images/image-waffle-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-waffle-thumbnail.jpg',
  },
  {
    title: 'Vanilla bean crème brûlée',
    category: 'Crème brûlée',
    price: 7.0,
    imgMobile: '/src/assets/images/image-creme-brulee-mobile.jpg',
    imgTablet: '/src/assets/images/image-creme-brulee-tablet.jpg',
    imgDesktop: '/src/assets/images/image-creme-brulee-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-creme-brulee-thumbnail.jpg',
  },
  {
    title: 'Macaron Mix of Five',
    category: 'Macaron',
    price: 8.0,
    imgMobile: '/src/assets/images/image-macaron-mobile.jpg',
    imgTablet: '/src/assets/images/image-macaron-tablet.jpg',
    imgDesktop: '/src/assets/images/image-macaron-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-macaron-thumbnail.jpg',
  },
  {
    title: 'Classic Tiramisa',
    category: 'Tiramisa',
    price: 5.5,
    imgMobile: '/src/assets/images/image-tiramisu-mobile.jpg',
    imgTablet: '/src/assets/images/image-tiramisu-tablet.jpg',
    imgDesktop: '/src/assets/images/image-tiramisu-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-tiramisu-thumbnail.jpg',
  },
  {
    title: 'Pistachio Baklava',
    category: 'Baklava',
    price: 4.0,
    imgMobile: '/src/assets/images/image-baklava-mobile.jpg',
    imgTablet: '/src/assets/images/image-baklava-tablet.jpg',
    imgDesktop: '/src/assets/images/image-baklava-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-baklava-thumbnail.jpg',
  },
  {
    title: 'Lemon Meringue Pie',
    category: 'Pie',
    price: 5.0,
    imgMobile: '/src/assets/images/image-meringue-mobile.jpg',
    imgTablet: '/src/assets/images/image-meringue-tablet.jpg',
    imgDesktop: '/src/assets/images/image-meringue-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-meringue-thumbnail.jpg',
  },
  {
    title: 'Red Velvet Cake',
    category: 'Cake',
    price: 4.5,
    imgMobile: '/src/assets/images/image-cake-mobile.jpg',
    imgTablet: '/src/assets/images/image-cake-tablet.jpg',
    imgDesktop: '/src/assets/images/image-cake-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-cake-thumbnail.jpg',
  },
  {
    title: 'Salted Caramel Brownie',
    category: 'Brownie',
    price: 4.5,
    imgMobile: '/src/assets/images/image-brownie-mobile.jpg',
    imgTablet: '/src/assets/images/image-brownie-tablet.jpg',
    imgDesktop: '/src/assets/images/image-brownie-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-brownie-thumbnail.jpg',
  },
  {
    title: 'Vanilla panna cotta',
    category: 'Panna Cotta',
    price: 6.5,
    imgMobile: '/src/assets/images/image-panna-cotta-mobile.jpg',
    imgTablet: '/src/assets/images/image-panna-cotta-tablet.jpg',
    imgDesktop: '/src/assets/images/image-panna-cotta-desktop.jpg',
    imgThumbnail: '/src/assets/images/image-panna-cotta-thumbnail.jpg',
  },
];
